# Generated by Django 3.1.13 on 2021-10-02 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('subreddit', models.CharField(db_index=True, max_length=50)),
                ('url', models.URLField()),
                ('data', models.JSONField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='datasets.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='RedditPostAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('notes', models.TextField(blank=True)),
                ('confidence', models.IntegerField(blank=True, choices=[(0, 'Not confident at all'), (1, 'Somehow confident'), (4, 'Very confident'), (5, 'Absolutely sure')], null=True)),
                ('options', models.ManyToManyField(null=True, related_name='annotations', to='projects.AnnotationOption')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='posts.redditpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reddit_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'post')},
            },
        ),
    ]
