# Generated by Django 3.1.13 on 2021-07-15 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0003_auto_20210715_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_utc', models.DateTimeField(blank=True, null=True)),
                ('subreddit', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='datasets.dataset')),
            ],
        ),
    ]
