# Generated by Django 3.1.13 on 2021-07-15 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redditpost',
            name='name',
        ),
        migrations.AddField(
            model_name='redditpost',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
