# Generated by Django 3.1.13 on 2021-10-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditpostannotation',
            name='options',
            field=models.ManyToManyField(related_name='annotations', to='projects.AnnotationOption'),
        ),
    ]
