# Generated by Django 3.1.13 on 2021-07-15 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0003_auto_20210715_1535'),
        ('posts', '0002_auto_20210715_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redditpost',
            old_name='created_utc',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='dataset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='datasets.dataset'),
        ),
    ]
