# Generated by Django 3.1.13 on 2021-09-29 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('datasets', '0003_auto_20210715_1535'),
        ('posts', '0003_auto_20210715_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnotationConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='annotation_config', to='datasets.dataset')),
            ],
        ),
        migrations.CreateModel(
            name='AnnotationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='posts.annotationconfig')),
            ],
        ),
        migrations.CreateModel(
            name='RedditPostAnnotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('notes', models.TextField()),
                ('options', models.ManyToManyField(related_name='annotations', to='posts.AnnotationOption')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='posts.redditpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reddit_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
