# Generated by Django 3.1.13 on 2021-09-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0004_annotationconfig_annotationoption'),
        ('posts', '0004_annotationconfig_annotationoption_redditpostannotation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotationoption',
            name='config',
        ),
        migrations.AlterField(
            model_name='redditpostannotation',
            name='options',
            field=models.ManyToManyField(related_name='annotations', to='datasets.AnnotationOption'),
        ),
        migrations.DeleteModel(
            name='AnnotationConfig',
        ),
        migrations.DeleteModel(
            name='AnnotationOption',
        ),
    ]
