# Generated by Django 3.1.13 on 2021-09-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210930_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='redditpostannotation',
            name='confidence',
            field=models.IntegerField(choices=[(0, 'Not confident at all'), (1, 'Somehow confident'), (4, 'Very confident'), (5, 'Absolutely sure')], default=1),
            preserve_default=False,
        ),
    ]
