# Generated by Django 3.1.13 on 2021-09-30 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasets', '0004_annotationconfig_annotationoption'),
        ('posts', '0006_redditpostannotation_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redditpostannotation',
            name='confidence',
            field=models.IntegerField(blank=True, choices=[(0, 'Not confident at all'), (1, 'Somehow confident'), (4, 'Very confident'), (5, 'Absolutely sure')], null=True),
        ),
        migrations.AlterField(
            model_name='redditpostannotation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='redditpostannotation',
            name='options',
            field=models.ManyToManyField(null=True, related_name='annotations', to='datasets.AnnotationOption'),
        ),
    ]
