# Generated by Django 3.1.13 on 2021-09-30 23:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_auto_20211001_0137'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='redditpostannotation',
            unique_together={('user', 'post')},
        ),
    ]
