name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: [ "master", "main" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "master", "main" ]
    paths-ignore: [ "docs/**" ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.12"
          cache: 'pip'

      # Run all pre-commit hooks on all the files.
      - name: Install and Run Pre-commit 
        uses: pre-commit/action@v3.0.1

  pytest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: etiketle
          POSTGRES_USER: etiketle
          POSTGRES_PASSWORD: etiketle
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4.1.1

      - name: Set up Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: "3.12"
          cache: 'pip'

      - name: Setup Database
        run: |
          psql -h localhost -U etiketle -d etiketle -c "ALTER USER etiketle CREATEDB;"
        env:
          PGPASSWORD: etiketle

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/local.txt

      - name: Run Tests
        env:
          DATABASE_URL: "postgres://etiketle:etiketle@localhost:5432/etiketle"
          DJANGO_SETTINGS_MODULE: config.settings.test
        run: |
          python -m pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false
          verbose: true
